# Generated by Django 5.2.3 on 2025-06-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_categories_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего отправленного напоминания'),
        ),
        migrations.AddField(
            model_name='task',
            name='remind_daily',
            field=models.BooleanField(default=False, verbose_name='Ежедневное напоминание'),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_intervals',
            field=models.JSONField(blank=True, default=list, help_text='Список интервалов напоминаний в минутах (например, [60, 1440] для напоминания за 1 час и 1 день)'),
        ),
    ]
