# Generated by Django 5.2.3 on 2025-06-19 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_last_reminder_sent_task_remind_daily_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.telegramuser', to_field='telegram_id'),
            preserve_default=False,
        ),
    ]
