version: '3.8'

services:
  web:
    build:
      context: ./backend/todolist
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/todolist:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - TZ=America/Adak
    depends_on:
      - db
      - redis

  worker:
    build:
      context: ./backend/todolist
    command: celery -A todolist worker --loglevel=info
    volumes:
      - ./backend/todolist:/app
    env_file:
      - ./.env
    environment:
      - TZ=America/Adak
    depends_on:
      - db
      - redis

  beat:
    build:
      context: ./backend/todolist
    command: celery -A todolist beat --loglevel=info
    volumes:
      - ./backend/todolist:/app
    env_file:
      - ./.env
    environment:
      - TZ=America/Adak
    depends_on:
      - db
      - redis

  bot:
    build:
      context: ./bot
    command: python bot_main.py
    volumes:
      - ./bot:/app
    env_file:
      ./.env
    environment:
      - TZ=America/Adak
    depends_on:
      - web
      - redis

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:7
    restart: always

volumes:
  postgres_data:
